server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: sticker-art-gallery
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
          max-tokens: 1000
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway управляет схемой в продакшне
    show-sql: false  # Отключаем SQL логи в продакшне
  
  # Flyway для production
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: false  # В продакшне базовая миграция должна быть применена явно

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true

app:
  url: ${APP_URL}
  mini-app:
    url: ${MINI_APP_URL:${app.url}/mini-app/}
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}

telegram:
  bot:
    token: ${TELEGRAM_API_TOKEN}
    name: ${TELEGRAM_BOT_NAME}
    webhook:
      url: ${BOT_WEBHOOK_URL}

logging:
  level:
    root: INFO
    com.example.sticker_art_gallery: INFO
    com.example.sticker_art_gallery.service.telegram: WARN  # Уменьшаем логи при загрузке изображений
    com.example.sticker_art_gallery.service.proxy: WARN  # Уменьшаем логи прокси-запросов
    com.example.sticker_art_gallery.service.metrics: WARN  # Уменьшаем логи метрик
    com.example.sticker_art_gallery.controller.StickerProxyController: WARN  # Уменьшаем логи прокси-контроллера
    com.example.sticker_art_gallery.util: WARN  # Уменьшаем логи валидации
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.jdbc: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: WARN
    org.telegram: INFO
    org.flywaydb: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /data/app.log
    max-size: 10MB
    max-history: 7 