# Конфигурация для отключения тестов на проде
# Этот файл используется только в продакшен окружении

spring:
  # Отключаем все тесты на проде
  test:
    database:
      replace: none
    context:
      cache:
        max-size: 0  # Отключаем кэш тестового контекста
  
  # Отключаем автоконфигурацию тестов
  autoconfigure:
    exclude:
      - org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTestAutoConfiguration
      - org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTestAutoConfiguration
      - org.springframework.boot.test.autoconfigure.json.JsonTestAutoConfiguration

# Отключаем тестовые профили
spring.profiles.exclude: test, unit

# Логирование для продакшена
logging:
  level:
    org.springframework.test: OFF  # Полностью отключаем логи тестов
    org.junit: OFF
    org.gradle: OFF
    org.testcontainers: OFF
